---

  - name: create VM1 on Chameleon
    #ignore_errors: yes
    openstack.cloud.server:
      state: present
      auth:
       auth_url: https://kvm.tacc.chameleoncloud.org:5000/v3
       username: mills19
       project_name: CH-822922
       project_domain_name: chameleon
      region_name: "KVM@TACC"
      name: redis-vm1
      image: CC-Ubuntu18.04
      key_name: redis-test
      timeout: 100
      flavor: m1.xlarge
      floating_ips:
        - 129.114.25.240
      nics:
        - net-id: 50073c73-5817-49c3-8e3a-69b8c357e158
      security_groups:
       - default


  - name: create VM2 on Chameleon
    #ignore_errors: yes
    openstack.cloud.server:
      state: present
      auth:
       auth_url: https://kvm.tacc.chameleoncloud.org:5000/v3
       username: mills19
       password: goCommodore64!
       project_name: CH-822922
       project_domain_name: chameleon
      name: redis-vm2
      image: CC-Ubuntu18.04
      key_name: redis-test
      timeout: 100
      flavor: m1.xlarge
      nics:
        - net-id: 50073c73-5817-49c3-8e3a-69b8c357e158
      floating_ips:
        - 129.114.27.239
      security_groups:
       - default


  - name: Add VM1 to inventory
    add_host:
      hostname: redis-vm1
      groups: MyChameleonVMs
      ansible_host: 129.114.25.240
      ansible_connection: ssh
      ansible_user: cc
      ansible_ssh_private_key_file: ~/.ssh/redis-test.pem
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  - name: Add VM2 to inventory
    add_host:
      hostname: redis-vm2
      groups: MyChameleonVMs
      ansible_host: 129.114.27.239
      ansible_connection: ssh
      ansible_user: cc
      ansible_ssh_private_key_file: ~/.ssh/redis-test.pem
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  - name: Wait for CC to initialize
    wait_for:
        timeout: 45


... 

